name: Unicorn Brain Automation Tests
on: push

jobs:
  unicorn-brain-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust the Node.js version as needed

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Tests
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          newman run dev-unicorn-ai.postman_collection.json \
            -e non-prod.postman_environment.json \
            --env-var "client_secret=$CLIENT_SECRET" \
            --reporters json --reporter-json-export result.json  

      - name: Create Status Check based on Postman Results
        id: process-postman
        uses: im-open/process-postman-test-results@v2.1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: result.json
          report-name: 'Postman ${{ github.run_number }}'
          create-status-check: true
          create-pr-comment: false
          update-comment-if-one-exists: false
          ignore-test-failures: true
          timezone: 'america/denver'

      - name: Fail on Test Failures
        if: steps.process-postman.outputs.test-outcome == 'Failed'
        run: |
          echo "There were Postman test failures."
          exit 1
